/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as IdeasIndexRouteImport } from './routes/ideas.index'
import { Route as IdeasIdeaIdRouteImport } from './routes/ideas.$ideaId'
import { Route as IdeasNewRouteImport } from './routes/ideas.new'
import { Route as PeopleProfileIdRouteImport } from './routes/people.$profileId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as IdeasIdeaIdIndexRouteImport } from './routes/ideas.$ideaId.index'
import { Route as IdeasIdeaIdSpaceRouteImport } from './routes/ideas.$ideaId.space'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/ideas/',
  path: '/ideas/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaIdRoute = IdeasIdeaIdRouteImport.update({
  id: '/ideas/$ideaId',
  path: '/ideas/$ideaId',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasNewRoute = IdeasNewRouteImport.update({
  id: '/ideas/new',
  path: '/ideas/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleProfileIdRoute = PeopleProfileIdRouteImport.update({
  id: '/people/$profileId',
  path: '/people/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaIdIndexRoute = IdeasIdeaIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdeasIdeaIdRoute,
} as any)
const IdeasIdeaIdSpaceRoute = IdeasIdeaIdSpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => IdeasIdeaIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRouteWithChildren
  '/ideas/new': typeof IdeasNewRoute
  '/people/$profileId': typeof PeopleProfileIdRoute
  '/ideas/': typeof IdeasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ideas/$ideaId/space': typeof IdeasIdeaIdSpaceRoute
  '/ideas/$ideaId/': typeof IdeasIdeaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRoute
  '/ideas/new': typeof IdeasNewRoute
  '/people/$profileId': typeof PeopleProfileIdRoute
  '/ideas': typeof IdeasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ideas/$ideaId/space': typeof IdeasIdeaIdSpaceRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRouteWithChildren
  '/ideas/new': typeof IdeasNewRoute
  '/people/$profileId': typeof PeopleProfileIdRoute
  '/ideas/': typeof IdeasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ideas/$ideaId/space': typeof IdeasIdeaIdSpaceRoute
  '/ideas/$ideaId/': typeof IdeasIdeaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/inbox'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/teams'
    | '/ideas/$ideaId'
    | '/ideas/new'
    | '/people/$profileId'
    | '/ideas/'
    | '/api/auth/$'
    | '/ideas/$ideaId/space'
    | '/ideas/$ideaId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/inbox'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/teams'
    | '/ideas/new'
    | '/people/$profileId'
    | '/ideas'
    | '/api/auth/$'
    | '/ideas/$ideaId/space'
    | '/ideas/$ideaId'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/inbox'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/teams'
    | '/ideas/$ideaId'
    | '/ideas/new'
    | '/people/$profileId'
    | '/ideas/'
    | '/api/auth/$'
    | '/ideas/$ideaId/space'
    | '/ideas/$ideaId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  TeamsRoute: typeof TeamsRoute
  IdeasIdeaIdRoute: typeof IdeasIdeaIdRouteWithChildren
  IdeasNewRoute: typeof IdeasNewRoute
  PeopleProfileIdRoute: typeof PeopleProfileIdRoute
  IdeasIndexRoute: typeof IdeasIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/ideas'
      fullPath: '/ideas/'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideaId': {
      id: '/ideas/$ideaId'
      path: '/ideas/$ideaId'
      fullPath: '/ideas/$ideaId'
      preLoaderRoute: typeof IdeasIdeaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/new': {
      id: '/ideas/new'
      path: '/ideas/new'
      fullPath: '/ideas/new'
      preLoaderRoute: typeof IdeasNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$profileId': {
      id: '/people/$profileId'
      path: '/people/$profileId'
      fullPath: '/people/$profileId'
      preLoaderRoute: typeof PeopleProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideaId/': {
      id: '/ideas/$ideaId/'
      path: '/'
      fullPath: '/ideas/$ideaId/'
      preLoaderRoute: typeof IdeasIdeaIdIndexRouteImport
      parentRoute: typeof IdeasIdeaIdRoute
    }
    '/ideas/$ideaId/space': {
      id: '/ideas/$ideaId/space'
      path: '/space'
      fullPath: '/ideas/$ideaId/space'
      preLoaderRoute: typeof IdeasIdeaIdSpaceRouteImport
      parentRoute: typeof IdeasIdeaIdRoute
    }
  }
}

interface IdeasIdeaIdRouteChildren {
  IdeasIdeaIdSpaceRoute: typeof IdeasIdeaIdSpaceRoute
  IdeasIdeaIdIndexRoute: typeof IdeasIdeaIdIndexRoute
}

const IdeasIdeaIdRouteChildren: IdeasIdeaIdRouteChildren = {
  IdeasIdeaIdSpaceRoute: IdeasIdeaIdSpaceRoute,
  IdeasIdeaIdIndexRoute: IdeasIdeaIdIndexRoute,
}

const IdeasIdeaIdRouteWithChildren = IdeasIdeaIdRoute._addFileChildren(
  IdeasIdeaIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  TeamsRoute: TeamsRoute,
  IdeasIdeaIdRoute: IdeasIdeaIdRouteWithChildren,
  IdeasNewRoute: IdeasNewRoute,
  PeopleProfileIdRoute: PeopleProfileIdRoute,
  IdeasIndexRoute: IdeasIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
